### ISSUE TITLE
jbuilder/dune support?

### ISSUE THREAD

**Issue by pklehre** [hammerlab/ppx_deriving_cmdliner#30]
Can I build programs using ppx_deriving_cmdliner with jbuilder? Adding   

(preprocess (pps (ppx_deriving_cmdliner)))

does not seem to work.

**Comment by rgrinberg** [comment]
You cannot do this at the moment. `ppx_deriving_cmdliner` has a META file that is incompatible with omp's driver. So ppx_deriving_cmdliner itself would have to be ported to dune or the META needs to be fixed.
