### ISSUE TITLE
Default parameters

### ISSUE THREAD

**Issue by mthark** [hammerlab/ppx_deriving_cmdliner#31]
Hello,
I am trying to integrate default behaviour into my main program. When it is run in a terminal without any terminal commands I want the manpage to be printed. Is this kind of default behaviour already given in a function in ppx_deriving_cmdliner or is this an issue for the package cmdliner only?

**Comment by ihodes** [comment]
I believe this is something that would need to be addressed in Cmdliner. Apologies for the slow reply!
