### ISSUE TITLE
Scope of generated `[@ocaml.warning "-A"]` too narrow

### ISSUE THREAD

**Issue by jberdine** [hammerlab/ppx_deriving_cmdliner#34]
In the code generated, such as:
```
let rec (cmdliner_term : unit -> t Cmdliner.Term.t) =
  ((let open! Ppx_deriving_cmdliner_runtime in
  ...)
  [@ocaml.warning "-A"])
```
the warning attribute does not disable `Warning 39: unused rec flag.` on the first line.

**Comment by smondet** [comment]
For the historians:

The `[@ocaml.warning "-A"]` comes from the `ppx_deriving` lib:
https://github.com/ocaml-ppx/ppx_deriving/blob/44fca8b2569c0a9fc6b0cad63d6b0ceb168e9f91/src/ppx_deriving.cppo.ml#L206-L213
