### ISSUE TITLE
Deprecation of cmdliners converter type

### ISSUE THREAD

**Issue by pkel** [hammerlab/ppx_deriving_cmdliner#37]
Cmdliner's converter type is deprecated: https://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#TYPEconverter

In the future we have to generate converters using [`Arg.conv`](https://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#VALconv). My attempt to use such a converter with ppx_deriving_cmdliner version  0.4.1 resulted in a type error.

Is this already solved in #10 but not yet released?

**Comment by ihodes** [comment]
Would you mind sharing code that works & code that errors? I'm reacquainting myself with this lib, but e.g. https://github.com/hammerlab/ppx_deriving_cmdliner/blob/master/src/ppx_deriving_cmdliner.cppo.ml#L191 and the other two invocations of conv seem to use `Arg.conv`.

**Comment by pkel** [comment]
```ocaml
Random.self_init ()

type lucky_string = S of string

let lucky_string_conv =
  let parse str =
    if Random.float 1. < 0.5 then Error (`Msg "unlucky") else Ok (S str)
  and print fmt (S s) = Format.fprintf fmt "lucky string: %s/n" s in
  (* works: *)
  (parse, print)
  (* does not work: *)
  (* Cmdliner.Arg.conv ~docv:"STRING" (parse, print) *)

include struct
  [@@@ocaml.warning "-39"]

  type params =
    { number: int [@default 42] [@aka ["n"]]
    ; string_: lucky_string [@aka ["s"]] [@conv lucky_string_conv]
    }
  [@@deriving cmdliner]
end

let main {number; string_} =
  let S s = string_ in
  Printf.printf "%i: You've been lucky with \"%s\"\n%!" number s

let term = Cmdliner.Term.(const main $ params_cmdliner_term ())
let info = Cmdliner.(Term.info "ls")
let () = Cmdliner.(Term.exit @@ Term.eval (term, info))
```

**Comment by pkel** [comment]
> Would you mind sharing code that works & code that errors? I'm reacquainting myself with this lib, but e.g. https://github.com/hammerlab/ppx_deriving_cmdliner/blob/master/src/ppx_deriving_cmdliner.cppo.ml#L191 and the other two invocations of conv seem to use `Arg.conv`.

I see that the generated code calls  `Arg.conv`. In my opinion the `@conv` attribute should take an `'a conv`, i.e. the output of `Arg.conv`. This would allow the user to specify the `~docv` argument.

**Comment by ihodes** [comment]
@pkel let me know if the above works for you

**Comment by pkel** [comment]
This works and is exactly what I had in mind. Thanks a lot!
