### ISSUE TITLE
Port to the latest version of ppx_deriving

### ISSUE THREAD

**Issue by romildo** [hammerlab/ppx_deriving_cmdliner#47]
Please, port `ppx_deriving_cmdliner` to the latest version of `ppx_deriving`. That would make it possible to package it for [NixOS](https://nixos.org/).

See https://github.com/NixOS/nixpkgs/pull/111641#issuecomment-772291045

**Comment by trepetti** [comment]
Yes, I've been meaning to do this so new OCaml versions wouldn't break stuff as often going forward anyway. Will try to get to it this week.

**Comment by romildo** [comment]
Thanks for fixing this.
