### ISSUE TITLE
0.6.0 does not compile

### ISSUE THREAD

**Issue by mthark** [hammerlab/ppx_deriving_cmdliner#49]
Hey,
whenever I try to update `ppx_deriving_cmdliner`, I get the following error:
```
#=== ERROR while compiling ppx_deriving_cmdliner.0.6.0 ========================#
# context     2.1.0~rc2 | linux/x86_64 | ocaml-base-compiler.4.11.2 | https://opam.ocaml.org#d3b8ae21
# path        ~/.opam/4.11.2/.opam-switch/build/ppx_deriving_cmdliner.0.6.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ppx_deriving_cmdliner -j 11
# exit-code   1
# env-file    ~/.opam/log/ppx_deriving_cmdliner-40672-21de72.env
# output-file ~/.opam/log/ppx_deriving_cmdliner-40672-21de72.out
### output ###
#       ocamlc src/.ppx_deriving_cmdliner.objs/byte/ppx_deriving_cmdliner.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && $HOME/.opam/4.11.2/bin/ocamlc.opt -w -40 -w -9-16-27-39 -g -bin-annot -I src/.ppx_deriving_cmdliner.objs/byte -I $HOME/.opam/4.11.2/lib/ocaml-compiler-libs/common -I $HOME/.opam/4.11.2/lib/ocaml-compiler-libs/shadow -I $HOME/.opam/4.11.2/lib/ocaml-migrate-parsetree -I $HOME/.opam/4.11.2/lib/ocaml/compiler-libs -I $HOME/.opam/4.11.2/lib[...]
# File "src/ppx_deriving_cmdliner.ml", line 313, characters 39-77:
# 313 |         let e_type_path = Exp.constant (Pconst_string (type_path, loc, None)) in
#                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: The constructor Pconst_string expects 2 argument(s),
#        but is applied here to 3 argument(s)
```

The opam packages installed on my systems are the following:
```cmdliner                1.0.4        
dune                    2.9.0        
ocaml                   4.11.2       
ocaml-base-compiler     4.11.2      
ocaml-compiler-libs     v0.12.3      
ocaml-config            1           
ocaml-migrate-parsetree 1.8.0        
ocamlbuild              0.14.0       
ocamlfind               1.9.1       
ppx_deriving            4.5          
ppxlib                  0.15.0
```
Does anybody know how to resolve this problem? The underlying system is Ubuntu 20.04.

**Comment by trepetti** [comment]
Thank you for your detailed report. 

It appears that we have an error in how we specified dependencies when we moved to ppxlib. Looks like this change in `Pconst_string` (a familiar foe) in the ppxlib API actually only occurred [in the 0.18.0 revision](https://github.com/ocaml-ppx/ppxlib/compare/0.17.0...0.18.0) not the 0.14.0 minimum version requirement we have in our OPAM requirements: `"ppxlib" {>= "0.14.0"}`. Our tests must have been pulling more recent ppxlib versions by default and hiding this potential error.

I will bump our minimum ppxlib version requirement and get a new version out to OPAM today.

**Comment by mthark** [comment]
@trepetti Thank you for your quick reply.

**Comment by trepetti** [comment]
Update: @mseri pointed out we could just update the previous 0.6.0 release, so he went ahead and updated that for us. @mthark, you should shortly be able to update the OPAM repository and then reinstall 0.6.0, and that will pull the correct ppxlib version in with it (if you haven't manually run `opam upgrade ppxlib` already in the meantime on your own).
